import type { Client, ProductService, Budget, BudgetItem } from './types'

// Mock Clients
export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Juan Pérez',
    company: 'Restaurante El Sabor',
    email: 'juan@elsabor.com',
    phone: '+506 8888-1234',
    address: 'San José, Costa Rica',
    notes: 'Cliente frecuente, prefiere facturación mensual',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'María González',
    company: 'Hotel Vista Verde',
    email: 'maria@vistaverde.cr',
    phone: '+506 8888-5678',
    address: 'Guanacaste, Costa Rica',
    notes: 'Mantenimiento trimestral programado',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '3',
    name: 'Carlos Ramírez',
    company: 'Finca Orgánica Los Altos',
    email: 'carlos@losaltos.com',
    phone: '+506 8888-9012',
    address: 'Alajuela, Costa Rica',
    notes: 'Interesado en biodigestor grande',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
]

// Mock Products/Services
export const mockProducts: ProductService[] = [
  {
    id: '1',
    name: 'Biodigestor Residencial 600L',
    description: 'Sistema de tratamiento de aguas residuales para uso residencial',
    category: 'biodigesters',
    price: 850000,
    unit: 'unidad',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Biodigestor Comercial 1500L',
    description: 'Sistema de tratamiento para restaurantes y pequeños comercios',
    category: 'biodigesters',
    price: 1450000,
    unit: 'unidad',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Trampa de Grasa 500L',
    description: 'Separador de grasas para cocinas comerciales',
    category: 'grease_traps',
    price: 320000,
    unit: 'unidad',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Trampa de Grasa 1000L',
    description: 'Separador de grasas para restaurantes grandes',
    category: 'grease_traps',
    price: 580000,
    unit: 'unidad',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Mantenimiento Preventivo',
    description: 'Servicio de mantenimiento preventivo mensual',
    category: 'maintenance',
    price: 45000,
    unit: 'visita',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Limpieza de Trampa de Grasa',
    description: 'Servicio de limpieza y succión de trampa de grasa',
    category: 'maintenance',
    price: 75000,
    unit: 'servicio',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: 'Instalación Básica',
    description: 'Mano de obra para instalación estándar',
    category: 'other',
    price: 150000,
    unit: 'servicio',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Mock Budget Items
const mockBudgetItems1: BudgetItem[] = [
  {
    id: '1',
    budgetId: '1',
    productServiceId: '3',
    productService: mockProducts.find(p => p.id === '3'),
    quantity: 1,
    unitPrice: 320000,
    subtotal: 320000,
  },
  {
    id: '2',
    budgetId: '1',
    productServiceId: '7',
    productService: mockProducts.find(p => p.id === '7'),
    quantity: 1,
    unitPrice: 150000,
    subtotal: 150000,
  },
]

const mockBudgetItems2: BudgetItem[] = [
  {
    id: '3',
    budgetId: '2',
    productServiceId: '2',
    productService: mockProducts.find(p => p.id === '2'),
    quantity: 2,
    unitPrice: 1450000,
    subtotal: 2900000,
  },
  {
    id: '4',
    budgetId: '2',
    productServiceId: '4',
    productService: mockProducts.find(p => p.id === '4'),
    quantity: 3,
    unitPrice: 580000,
    subtotal: 1740000,
  },
  {
    id: '5',
    budgetId: '2',
    productServiceId: '7',
    productService: mockProducts.find(p => p.id === '7'),
    quantity: 5,
    unitPrice: 150000,
    subtotal: 750000,
  },
]

const mockBudgetItems3: BudgetItem[] = [
  {
    id: '6',
    budgetId: '3',
    productServiceId: '1',
    productService: mockProducts.find(p => p.id === '1'),
    quantity: 1,
    unitPrice: 850000,
    subtotal: 850000,
  },
]

// Mock Budgets
export const mockBudgets: Budget[] = [
  {
    id: '1',
    clientId: '1',
    client: mockClients.find(c => c.id === '1'),
    items: mockBudgetItems1,
    status: 'approved',
    notes: 'Instalación programada para próxima semana',
    total: 470000,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '2',
    clientId: '2',
    client: mockClients.find(c => c.id === '2'),
    items: mockBudgetItems2,
    status: 'sent',
    notes: 'Esperando aprobación del gerente',
    total: 5390000,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '3',
    clientId: '3',
    client: mockClients.find(c => c.id === '3'),
    items: mockBudgetItems3,
    status: 'draft',
    notes: 'Pendiente agregar costos de instalación',
    total: 850000,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
]
